# Upsample with Convolutional Neural Networks
* Two common types of layers that can be used in the generator model are : 
    * **upsample layer** : that simply doubles the dimensions of the input.
    * **transpose convolutional layer** : that performs an inverse convolution operation.
    
* A simple version of an unpooling or opposite pooling layer is called an **upsampling layer**.

Both of these layers can be used on a GAN to perform the required upsampling operation to transform a small input into a large image output.

## 1. Worked Example Using the *UpSampling2D* Layer
* The simplest way to upsample an input is to double each row and column.
* It can be added to a convolutional neural network and repeats the rows and columns provided as input in the output.

In [2]:
# example of using the upsampling layer
from numpy import asarray
from keras.models import Sequential
from keras.layers import UpSampling2D

# define input data
X = asarray([[1,2],[3,4]])

# show input data for context
print(X)

# reshape input data into one sample a sample with a channel
X = X.reshape((1,2,2,1)) # samples,rows,columns,channels

# define model
model = Sequential()
model.add(UpSampling2D(input_shape=(2,2,1)))

# summarize the model
model.summary()

# make a prediction with the model
yhat = model.predict(X)

# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4,4))

# summarize output
print(yhat)

# the layer has no parameters or model weights,because it is not learning anything,it is just doubling the input.

[[1 2]
 [3 4]]
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_1 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


## 2. Simple Generator Model With the *UpSampling2D* Layer
* To be useful in a GAN,each *UpSampling2D* layer must be followed by a *Conv2D* layer that will learn to interpret the doubled input and be trained to translate it into meaningful detail.

In [4]:
# example of using upsampling in a simple generator model
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import UpSampling2D
from keras.layers import Conv2D

# define model
model = Sequential()

# define input shape,output enough activations for 128 5x5 image
model.add(Dense(128 * 5 * 5,input_dim=100))
# reshape vector of activations into 128 feature maps with 5x5
model.add(Reshape((5,5,128)))
# double input from 128 5x5 to 1 10x10 feature map
model.add(UpSampling2D())
# fill in detail in the upsampled feature maps and output a single image
model.add(Conv2D(1,(3,3),padding='same'))
# summarize model
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape (Reshape)            (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_2 (UpSampling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


## 3. Worked Example Using the *Conv2DTranspose* Layer
* The Conv2DTranspose both upsamples and performs a convolution.

In [5]:
# example of using the transpose convolutional layer
from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv2DTranspose

# define input data
X = asarray([[1,2],[3,4]])
# show input data for context
print(X)

# reshape input data into one sample a sample with a channel
X = X.reshape((1,2,2,1))

# define model
model = Sequential()
model.add(Conv2DTranspose(1,(1,1),strides=(2,2),input_shape=(2,2,1)))
# summarize the model
model.summary()
# define weights that they do nothing
weights = [asarray([[[[1]]]]),asarray([0])]
# store the weights in the model
model.set_weights(weights)
# make a prediction with the model
yhat = model.predict(X)
# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4,4))
# summarize output
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose (Conv2DTran (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]
